services:
  - type: web
    name: FakeProductDetector
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: python app.py
    build:
      environment:
        pythonVersion: 3.10.13

