services:
  - type: web
    name: FakeProductDetector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    region: oregon
    plan: free
    branch: main
